### ISSUE TITLE
Filling the DB

### ISSUE THREAD

**Issue by Japje** [julcollas/django-vsphere#1]
Hello Julien,

I would be very interested in the code how to fill this nice looking Model.
Are you able/willing to share this?

Gr,

Jasper

**Comment by julcollas** [comment]
Hi,

I'm pleased to share the import script.
Have a look to the "tools" directory I just pushed.

Commit: fac987a12722d6a58877868641f5c6522c93ea79

Let me know your result.

Regards,

Julien
